version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: archangel_postgres
    environment:
      POSTGRES_USER: archangel
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: archangelcs
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    restart: unless-stopped

  app:
    build: .
    container_name: archangel_app
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: archangel
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: archangelcs
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      JOIN_KEY: ${JOIN_KEY}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    restart: unless-stopped

volumes:
  postgres_data:
